const stuffArr = [
    {
     "class":"",
     "height":14.75,
     "id":33,
     "name":"pluto",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uc5b4\ub514\ub85c \uc5f0\uacb0\ub418\ub294 \ubb38\uc77c\uae4c?"
            }, 
            {
             "name":"isDead",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"isKeyborad",
             "type":"bool",
             "value":true
            }, 
            {
             "name":"isPortal",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }, 
            {
             "name":"nextStage",
             "type":"string",
             "value":""
            }, 
            {
             "name":"notAvailableMsg",
             "type":"string",
             "value":"\ub098\uac08 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."
            }, 
            {
             "name":"pw",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":25.75,
     "x":426.833,
     "y":225.458
    }, 
    {
     "class":"",
     "height":14.75,
     "id":45,
     "name":"\uc5d8\ub9ac\ubca0\uc774\ud130",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uace0\uc7a5\ub09c \uc5d8\ub9ac\ubca0\uc774\ud130"
            }, 
            {
             "name":"isDead",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"isKeyborad",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"isPortal",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }, 
            {
             "name":"nextStage",
             "type":"string",
             "value":""
            }, 
            {
             "name":"notAvailableMsg",
             "type":"string",
             "value":"\uc5d8\ub9ac\ubca0\uc774\ud130\ub97c \uc774\uc6a9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."
            }, 
            {
             "name":"pw",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":39.25,
     "x":292.375,
     "y":224.625
    }, 
    {
     "class":"",
     "height":14.75,
     "id":46,
     "name":"earth",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uc5b4\ub514\ub85c \uc5f0\uacb0\ub418\ub294 \ubb38\uc77c\uae4c?"
            }, 
            {
             "name":"isDead",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"isKeyborad",
             "type":"bool",
             "value":true
            }, 
            {
             "name":"isPortal",
             "type":"bool",
             "value":true
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }, 
            {
             "name":"nextStage",
             "type":"string",
             "value":"2"
            }, 
            {
             "name":"notAvailableMsg",
             "type":"string",
             "value":"\ub098\uac08 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."
            }, 
            {
             "name":"pw",
             "type":"string",
             "value":"heart"
            }],
     "rotation":0,
     "visible":true,
     "width":25.75,
     "x":555.125,
     "y":224.625
    }, 
    {
     "class":"",
     "height":14.75,
     "id":47,
     "name":"mercury",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uc5b4\ub514\ub85c \uc5f0\uacb0\ub418\ub294 \ubb38\uc77c\uae4c?"
            }, 
            {
             "name":"isDead",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"isKeyborad",
             "type":"bool",
             "value":true
            }, 
            {
             "name":"isPortal",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }, 
            {
             "name":"nextStage",
             "type":"string",
             "value":""
            }, 
            {
             "name":"notAvailableMsg",
             "type":"string",
             "value":"\ub098\uac08 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."
            }, 
            {
             "name":"pw",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":25.75,
     "x":683.625,
     "y":224.625
    }, 
    {
     "class":"",
     "height":14.75,
     "id":48,
     "name":"\ubb38",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uc5b4\ub514\ub85c \uc5f0\uacb0\ub418\ub294 \ubb38\uc77c\uae4c?"
            }, 
            {
             "name":"isDead",
             "type":"bool",
             "value":true
            }, 
            {
             "name":"isKeyborad",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"isPortal",
             "type":"bool",
             "value":false
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }, 
            {
             "name":"nextStage",
             "type":"string",
             "value":""
            }, 
            {
             "name":"notAvailableMsg",
             "type":"string",
             "value":"\ub098\uac08 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."
            }, 
            {
             "name":"pw",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":25.75,
     "x":778.625,
     "y":145.625
    }],
"opacity":1,
"type":"objectgroup",
"visible":false,
"x":0,
"y":0
}, 
{
"draworder":"topdown",
"id":30,
"name":"Stuff",
"objects":[
    {
     "class":"",
     "height":16,
     "id":4,
     "name":"\uc11c\ub78d",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uc11c\ub78d \uc548\uc5d0\ub294 \ubb34\uc5c7\uc774 \ub4e4\uc5b4\uc788\uc744\uae4c"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":15.3333,
     "x":400.667,
     "y":224
    }, 
    {
     "class":"",
     "height":15.3333,
     "id":8,
     "name":"\uc11c\ub78d\uc7a5",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc544\ubcf4\uc774\ub294 \uc11c\ub78d\uc774\ub2e4. \ubb34\uc5c7\uc774 \ub4e4\uc5b4\uc788\uc744\uae4c"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":30.3333,
     "x":593,
     "y":224
    }, 
    {
     "class":"",
     "height":15.75,
     "id":12,
     "name":"\ud611\ud0c1",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc740 \uc870\ud654\uac00 \uc62c\ub77c\uac00 \uc788\ub294 \ud611\ud0c1"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":"\uad6c\uae09\uc57d"
            }],
     "rotation":0,
     "visible":true,
     "width":15,
     "x":753,
     "y":144.25
    }, 
    {
     "class":"",
     "height":23.75,
     "id":17,
     "name":"\ud611\ud0c1",
     "rotation":0,
     "visible":true,
     "width":16.25,
     "x":592.25,
     "y":368.25
    }, 
    {
     "class":"",
     "height":15,
     "id":18,
     "name":"\ub9c1\uac70",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ud608\uc561\ud329 \ub0a1\uc740 \ub9c1\uac70. \ub179\uc2ac\uc5b4\ubcf4\uc778\ub2e4. "
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":15,
     "x":688.5,
     "y":368.5
    }, 
    {
     "class":"",
     "height":15.5,
     "id":20,
     "name":"\ub9c1\uac70",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc740 \ub9c1\uac70. \ub179\uc2ac\uc5b4\ubcf4\uc778\ub2e4."
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":15.75,
     "x":368,
     "y":320.25
    }, 
    {
     "class":"",
     "height":45.5,
     "id":22,
     "name":"\uc11c\ub78d\uc7a5",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc544\ubcf4\uc774\ub294 \uc11c\ub78d\uc774\ub2e4. \ubb34\uc5c7\uc774 \ub4e4\uc5b4\uc788\uc744\uae4c"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":13.5,
     "x":817.5,
     "y":273
    }, 
    {
     "class":"",
     "height":60,
     "id":23,
     "name":"\uac1c\uc218\ub300",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":" \ub0a1\uc740 \uac1c\uc218\ub300 \ubd88\ucf8c\ud574\ubcf4\uc774\ub294 \ubb34\uc5b8\uac00\uac00 \ub9d0\ub77c\ubd99\uc740 \uc790\uad6d\uc774 \ubcf4\uc778\ub2e4."
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":13,
     "x":273,
     "y":304
    }, 
    {
     "class":"",
     "height":32.5,
     "id":24,
     "name":"\uc11c\ub78d\uc7a5",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc544\ubcf4\uc774\ub294 \uc11c\ub78d\uc774\ub2e4. \ubb34\uc5c7\uc774 \ub4e4\uc5b4\uc788\uc744\uae4c"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":13,
     "x":273.5,
     "y":365.5
    }, 
    {
     "class":"",
     "height":17.3333,
     "id":25,
     "name":"\uc11c\ub78d\uc7a5",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc544\ubcf4\uc774\ub294 \uc11c\ub78d\uc774\ub2e4. \ubb34\uc5c7\uc774 \ub4e4\uc5b4\uc788\uc744\uae4c"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":"\uc5d1\uc2a4\ub808\uc774 \ud544\ub984"
            }],
     "rotation":0,
     "visible":true,
     "width":31.6667,
     "x":480.333,
     "y":222.666
    }, 
    {
     "class":"",
     "height":17.3333,
     "id":28,
     "name":"\uc11c\ub78d\uc7a5",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc544\ubcf4\uc774\ub294 \uc11c\ub78d\uc774\ub2e4. \ubb34\uc5c7\uc774 \ub4e4\uc5b4\uc788\uc744\uae4c"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":31.6667,
     "x":512.833,
     "y":223.333
    }, 
    {
     "class":"",
     "height":15,
     "id":29,
     "name":"\uc2dc\uacc4",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\uace0\uc7a5\ub09c \uc2dc\uacc4"
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":15,
     "x":656.5,
     "y":224.25
    }, 
    {
     "class":"",
     "height":14.75,
     "id":32,
     "name":"\uac8c\uc2dc\ud310",
     "properties":[
            {
             "name":"infoMsg",
             "type":"string",
             "value":"\ub0a1\uc544\ubcf4\uc774\ub294 \uac8c\uc2dc\ud310 \uc790\uc138\ud788 \ubcf4\uba74 \ubb54\uac00\uac00 \ubcf4\uc77c \uac83 \uac19\ub2e4. \"body\"\ub77c\uace0 \ubaa8\uc11c\ub9ac\uc5d0 \uc801\ud600\uc788\ub2e4."
            }, 
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":25.25,
     "x":371.708,
     "y":227.958
    }, 
    {
     "class":"",
     "height":15.75,
     "id":44,
     "name":"\uad6c\uae09\ud568",
     "properties":[
            {
             "name":"item",
             "type":"string",
             "value":""
            }],
     "rotation":0,
     "visible":true,
     "width":14.75,
     "x":720.625,
     "y":224.125
    }],
"opacity":1,
"type":"objectgroup",
"visible":false,
"x":0,
"y":0
}];